[book]
authors = ["Lam Nguyen"]
language = "en"
multilingual = false
src = "."
title="Learn GenerativeAI from Zero to Hero"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
mathjax-support = false
git-repository-url = "https://github.com/mlip-cmu/book"
git-repository-icon = "fa-github"

[build]
extra-watch-dirs = ["README.md"] 

[output.html.redirect]
"/01/index.html" = "../01-introduction.html"
"/02/index.html" = "../02-Fundamental.html"
